package:
  name: pyside-pyzo
  version: 1.2.1

source:
  fn: PySide-1.2.1.tar.gz       [unix]
  url: http://download.qt-project.org/official_releases/pyside/PySide-1.2.1.tar.gz              [unix]
  
  url: file:\\E:\pyzodistrofiles\conda-package-sources\PySide-1.2.1.win32-py3.3.zip  [win32]
  fn: PySide-1.2.1.win32-py3.3.zip           [win32 and py33]
  url: file:\\F:\pyzodistrofiles\conda-package-sources\PySide-1.2.1.win-amd64-py3.3.zip  [win64]
  fn: PySide-1.2.1.win-amd64-py3.3.zip       [win64 and py33]

build:
  number: 6    [linux]
  number: 4    [osx]
  number: 1    [win]

requirements:
  build:
    - cmake     [unix]
    #- qt        [linux]  # Not on Mac, maybe do same approach on Linux?
    - libpng    [linux]
    - python
  run:
    #- qt        [linux]
    - libpng    [linux]
    - python
    #- python.app  [osx]

about:
    home: https://pypi.python.org/pypi/PySide
    license: LGPL
