package:
  name: cx_freeze
  version: 4.3.3

source:
  fn: cx_Freeze-4.3.3.tar.gz [unix]
  url: https://pypi.python.org/packages/source/c/cx_Freeze/cx_Freeze-4.3.3.tar.gz [unix]
  md5: 3cae24b98694540eb083ac500c0d4aa1 [unix]
  
  url: https://dl.dropboxusercontent.com/u/1463853/conda-package-sources/cx_Freeze-4.3.3.win32-py3.4.zip [win32]
  fn: cx_Freeze-4.3.3.win32-py3.4.zip [win32]
  url: hhttps://dl.dropboxusercontent.com/u/1463853/conda-package-sources/cx_Freeze-4.3.3.win-amd64-py3.4.zip [win64]
  fn: ccx_Freeze-4.3.3.win-amd64-py3.4.zip [win64]
  

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - cx_Freeze

about:
  home: http://cx-freeze.sourceforge.net/
  license: cx-freeze license

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
