package:
  name: iep
  version: 3.5

source:
  fn: iep-3.5.tar.gz
  url: https://pypi.python.org/packages/source/i/iep/iep-3.5.tar.gz
  md5: 5bd4376e5fecd9b83baac89a556a92d1

requirements:
  build:
    - python

  run:
    - pyzolib
    - python

test:
  # Python imports
  imports:
    # We would need either pyside or pyqt4, so we can not really test
    #- iep


about:
  home: http://iep-project.org
  license: BSD

