package:
  name: iep
  version: 3.3.2

source:
  fn: iep-3.3.2.tar.gz
  url: https://pypi.python.org/packages/source/i/iep/iep-3.3.2.tar.gz
  md5: 09d49128de24724cfaee2145de5500e0

requirements:
  build:
    - python

  run:
    - pyzolib
    - python

test:
  # Python imports
  imports:
    # We would need either pyside or pyqt4, so we can not really test
    #- iep


about:
  home: http://iep-project.org
  license: BSD

