package:
  name: iep
  version: 3.6

source:
  fn: iep-3.6.tar.gz
  url: https://pypi.python.org/packages/source/i/iep/iep-3.6.tar.gz
  md5: ebd7fee35decb1a472839825c6b7feb9

build:
  number: 2

requirements:
  build:
    - pyzolib
    - python

  run:
    - pyzolib
    - python

test:
  # Python imports
  imports:
    # We would need either pyside or pyqt4, so we can not really test
    #- iep


about:
  home: http://iep-project.org
  license: BSD

