package:
  name: iep
  version: 3.3.1

source:
  fn: iep-3.3.1.tar.gz
  url: https://pypi.python.org/packages/source/i/iep/iep-3.3.1.tar.gz
  md5: b2271ddaf880b49a4bac55172f191148

requirements:
  build:
    - python

  run:
    - pyzolib
    - python

test:
  # Python imports
  imports:
    # We would need either pyside or pyqt4, so we can not really test
    #- iep


about:
  home: http://iep-project.org
  license: BSD

