package:
  name: imageio
  version: 0.5

source:
  fn: imageio-0.5.tar.gz
  url: https://pypi.python.org/packages/source/i/imageio/imageio-0.5.tar.gz
  md5: f002efc78e07b0925d0e2acbe5de0205

requirements:
  build:
    - python

  run:
    #- numpy do not put here, since conda will stick it to a specific version
    - python
  
test:
  # Python imports
  imports:
  #  - imageio I believe it (conda will not include numpy in test env)

about:
  home: http://imageio.readthedocs.org
  license: BSD

