package:
  name: imageio
  version: 0.4.1

source:
  fn: imageio-0.4.1.tar.gz
  url: https://pypi.python.org/packages/source/i/imageio/imageio-0.4.1.tar.gz
  md5: 1d12234fed1d8859d983efa56a80cd8e

requirements:
  build:
    - python

  run:
    #- numpy do not put here, since conda will stick it to a specific version
    - python
  
test:
  # Python imports
  imports:
  #  - imageio I believe it (conda will not include numpy in test env)

about:
  home: http://imageio.readthedocs.org
  license: BSD

