package:
  name: imageio
  version: 1.1

source:
  fn: imageio-1.1.zip
  url: https://pypi.python.org/packages/source/i/imageio/imageio-1.1.zip
  #md5: fcdfa0d13d7ce2cf06f2f34f8cae3c19

requirements:
  build:
    - python

  run:
    #- numpy do not put here, since conda will stick it to a specific version
    - python
  
test:
  # Python imports
  imports:
  #  - imageio I believe it (conda will not include numpy in test env)

about:
  home: http://imageio.readthedocs.org
  license: BSD

