package:
  name: pyzolib
  version: 0.2.5

source:
  fn: pyzolib-0.2.5.tar.gz
  url: https://pypi.python.org/packages/source/p/pyzolib/pyzolib-0.2.5.tar.gz
  md5: f5718b584f3467490674e17d631cb8dd

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - pyzolib
    - pyzolib.path
    - pyzolib.paths
    - pyzolib.qt
    - pyzolib.interpreters


about:
  home: http://bitbucket.org/pyzo/pyzolib
  license: BSD

