package:
  name: pyzolib
  version: 0.2.9

source:
  fn: pyzolib-0.2.9.tar.gz
  url: https://pypi.python.org/packages/source/p/pyzolib/pyzolib-0.2.9.tar.gz
  md5: 699ec58ee945584ba979f2af586ac354

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - pyzolib
    - pyzolib.path
    - pyzolib.paths
    - pyzolib.qt
    - pyzolib.interpreters


about:
  home: http://bitbucket.org/pyzo/pyzolib
  license: BSD

