package:
  name: pyzolib
  version: 0.2.7

source:
  fn: pyzolib-0.2.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pyzolib/pyzolib-0.2.7.tar.gz
  md5: 2a9618538ce80fd948e1338d869e8a9f

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - pyzolib
    - pyzolib.path
    - pyzolib.paths
    - pyzolib.qt
    - pyzolib.interpreters


about:
  home: http://bitbucket.org/pyzo/pyzolib
  license: BSD

